export let technologyIcons = [
    '<i class="fab fa-react" data-tech="react" data-id="first"></i>',
    '<i class="fab fa-react" data-tech="react" data-id="second"></i>',
    '<i class="fab fa-vuejs" data-tech="vue" data-id="first"></i>',
    '<i class="fab fa-vuejs" data-tech="vue" data-id="second"></i>',
    '<i class="fab fa-html5" data-tech="html" data-id="first"></i>',
    '<i class="fab fa-html5" data-tech="html" data-id="second"></i>',
    '<i class="fab fa-css3-alt" data-tech="css" data-id="first"></i>',
    '<i class="fab fa-css3-alt" data-tech="css" data-id="second"></i>',
    '<i class="fab fa-js-square" data-tech="js" data-id="first"></i>',
    '<i class="fab fa-js-square" data-tech="js" data-id="second"></i>',
    '<i class="fab fa-angular" data-tech="angular" data-id="first"></i>',
    '<i class="fab fa-angular" data-tech="angular" data-id="second"></i>',
    '<i class="fab fa-python" data-tech="python" data-id="first"></i>',
    '<i class="fab fa-python" data-tech="python" data-id="second"></i>',
    '<i class="fab fa-php" data-tech="php" data-id="first"></i>',
    // '<i class="fab fa-php" data-tech="php" data-id="second"></i>',
];